### ISSUE TITLE
alfabetical

### ISSUE THREAD

**Issue by kud** [sindresorhus/cat-names#1]
![giphy](https://cloud.githubusercontent.com/assets/655838/5742695/6f607d58-9c14-11e4-8453-7bc9e88707ae.gif)

**Comment by sindresorhus** [comment]
``` js
var catNames = require('cat-names');

var sorted = catNames.all.slice().sort(function (a, b) {
  return a.localeCompare(b);
});
```

**Comment by MoOx** [comment]
Is it not `alphabetical` ?

**Comment by kud** [comment]
Well. It's more about… README.md you know.

```
Top 100 cat names in alfabetical order.
```

❯❯❯ http://www.thefreedictionary.com/alphabetical

**Comment by sindresorhus** [comment]
Oh, I thought I was on the dogs one.

And yeah, I can't spell: https://github.com/sindresorhus/cat-names/commit/28d0225c94b764fcd5aafab1e597de79598b527f

**Comment by kud** [comment]
Thank you @sindresorhus ;)
