### ISSUE TITLE
No Ferguson 

### ISSUE THREAD

**Issue by dortzur** [sindresorhus/cat-names#5]
Gotta have Ferguson.
![tumblr_mtp0ohobxj1rmg5uao1_250](https://cloud.githubusercontent.com/assets/419875/5834185/9664d76a-a163-11e4-8c13-086ca750a7ae.gif)

**Comment by sindresorhus** [comment]
Lol, yeah, probably, but this list is the most popular names. Poor ferguson didn't make it.
