### ISSUE TITLE
Optional random() argument

### ISSUE THREAD

**Issue by kutyel** [sindresorhus/cat-names#9]
Hi!

I found the project very funny and interesting! But I would like to propose an improvement...

As a lover of cats, I might have in mind by which **letter** I want the name of my pet to start, even though I have no clue of the full name:

``` javascript
const catNames = require('cat-names');

catNames.random('W'); // > 'Whiskers'
```

---

_PD:_ why no PR with new names? My :cat2: is called **Schrödinger**, I think it's an awesome name! :smile:

**Comment by sindresorhus** [comment]
Glad you like it. The `.random` function is just for convenience. Not really interested in adding anything more. The main thing here is the list. You're free to create additional modules making use of the data. 

> why no PR with new names?

I sourced the names from the 100 most popular cat names of 2015 or something. If I opened up submissions everyone would submit their cat name, and cats can be named pretty much anything, and I don't have the time to manage all those submissions. You could always create your own fork of this module with more names. For my needs, 100 names is more than enough though.
